### ISSUE TITLE
S3 Client customer logger doesn't print debug message properly

### ISSUE THREAD

**Issue by king4sam** [smithy-lang/smithy-typescript#1267]
[S3 Client customer logger doesn't print debug message properly #4650](https://github.com/aws/aws-sdk-js-v3/issues/4650)

There was a previous issue fixed. However, I found that the following files are still printing only 'endpoints' without useful debug messages.

packages/util-endpoints/utils/evaluateEndpointRule.ts
packages/util-endpoints/utils/evaluateConditions.ts
packages/util-endpoints/utils/evaluateCondition.ts

I would apply the same patch to these files.

**Comment by syall** [comment]
Generally, the `Logger` interface methods use [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters). If you see only `endpoints`, it is probably due to the logger implementation only looking at the first argument rather than all of them.

That being said, I think it's ok to make the messages print a single string in the spots you mentioned.

**Comment by king4sam** [comment]
Based on my understanding, pino and winston are two of the most popular logging libraries for Node.js. 
While they do not follow strictly the logger interface, it would be beneficial for greater compatibility with these widely-used options.

**Comment by syall** [comment]
#1268 was merged, closing this issue.
